### ISSUE TITLE
not reading data

### ISSUE THREAD

**Issue by rw86347** [Thijxx/TinyHead#1]
Attached you will find oscilloscope traces.

As you can see from the oscilloscope readings I have data leaving chip 1 and being received by radio 2.  You will also notice from the picture that each bit is 4.2ms wide and has a ramp up time of 1.8ms.  I am touching my probe to D2 as seen on the attached image.  I know my serial is working because the word "up" comes in on my monitor at boot time.

Any ideas what might be going wrong?

OH BTW I slowed the data down to 250 because at 2000 I couldn't even recognize the data.

`// ask_receiver.pde
// -*- mode: C++ -*-
// Simple example of how to use RadioHead to receive messages
// with a simple ASK transmitter in a very simple way.
// Implements a simplex (one-way) receiver with an Rx-B1 module

#include <RH_ASK.h>
#include <SoftwareSerial.h>

#define RX 3
#define TX 1

SoftwareSerial Serial(RX, TX);

//RH_ASK driver;
RH_ASK driver(250, 2, 4, 5); // ESP8266: do not use pin 11

void setup() {
    Serial.begin(9600);
    driver.init();
    Serial.print("up\n");
}

void loop() {
    uint8_t buf[RH_ASK_MAX_MESSAGE_LEN];
    uint8_t buflen = sizeof(buf);

    if (driver.recv(buf, &buflen)) { // Non-blocking
        int i;

        // Message with a good checksum received, dump it.
        Serial.write(buf, buflen);
        Serial.print("\n");
    }
}`
![sds00005](https://user-images.githubusercontent.com/324117/31359087-b150b0ca-ad05-11e7-82a6-7b00fdfd9728.jpg)
![sds00006](https://user-images.githubusercontent.com/324117/31359088-b15dfb72-ad05-11e7-9ac3-8955d5694199.jpg)
![52713d5b757b7fc0658b4567](https://user-images.githubusercontent.com/324117/31359089-b15ee424-ad05-11e7-81dd-5f590704147a.png)

**Comment by Thijxx** [comment]
Not sure if you can use `SoftwareSerial` with this because of the single `Timer` and `RadioHead` needs it so they will fight over it (read: it will not work). In my tests I use a blinking LED and in my example code I do not use the `SoftwareSerial`.

Would you please try it without?

**Comment by Thijxx** [comment]
Can I close this?
